# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 13:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='Enter_Useranme', max_length=16, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UploadAdvetisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_Advertisement', models.FileField(upload_to='uploads/')),
                ('time_of_advertisement', models.IntegerField(default=30)),
                ('no_of_slots', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('select_bundles', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('no_of_weeks', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('bussinessPoint_longitude', models.DecimalField(decimal_places=15, default=0, max_digits=18)),
                ('bussinessPoint_latitude', models.DecimalField(decimal_places=15, default=0, max_digits=18)),
                ('start_week', models.DateTimeField(default=datetime.datetime(2016, 10, 27, 13, 9, 20, 580692, tzinfo=utc), verbose_name='Starting week of the advertisement')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
