# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='Enter_Useranme', max_length=40, unique=True)),
                ('password', models.CharField(max_length=62)),
            ],
        ),
        migrations.CreateModel(
            name='UploadAdvetisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_Advertisement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('time_of_advertisement', models.IntegerField(default=30)),
                ('no_of_slots', models.IntegerField(default=1)),
                ('no_of_repeats', models.IntegerField(default=1)),
                ('select_bundles', models.IntegerField(default=1)),
                ('no_of_weeks', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('bussinessPoint_longitude', models.DecimalField(decimal_places=15, default=0, max_digits=18)),
                ('bussinessPoint_latitude', models.DecimalField(decimal_places=15, default=0, max_digits=18)),
                ('start_week', models.DateTimeField(default=datetime.datetime(2016, 11, 3, 12, 31, 27, 470762, tzinfo=utc), verbose_name='Starting week of the advertisement')),
                ('amount_paid', models.IntegerField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_Advertisement', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.UploadAdvetisement')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('ad_type', models.CharField(choices=[('1', 'RealEstate'), ('2', 'clothing'), ('3', 'Jewellery'), ('4', 'Movies'), ('5', 'TV'), ('6', 'radio'), ('7', 'footwear'), ('8', 'malls'), ('9', 'airport'), ('10', 'food'), ('11', 'fashion'), ('12', 'electronics'), ('13', 'pharmacy'), ('14', 'hospital'), ('15', 'print_media'), ('16', 'Banks'), ('17', 'Theme parks'), ('18', 'Tourism'), ('19', 'Travel'), ('21', 'E-Commerce'), ('22', 'Telephone'), ('23', 'Mobiles'), ('24', 'Grocers'), ('25', 'Computers & Accesories'), ('26', 'Sports-Outdoors'), ('27', 'Furniture'), ('28', 'others')], default=1, max_length=120)),
                ('address', models.TextField(default='Address', max_length=500)),
                ('city', models.CharField(default='Hyderabad', max_length=100)),
                ('pincode', models.IntegerField(default=500032)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
