# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='start_week',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 27, 13, 44, 43, 882390, tzinfo=utc), verbose_name='Starting week of the advertisement'),
        ),
    ]
