# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userprofile_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password2',
        ),
    ]
