# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20161028_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='start_week',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 28, 13, 8, 19, 103506, tzinfo=utc), verbose_name='Starting week of the advertisement'),
        ),
    ]
