# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20161028_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='start_week',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 29, 6, 33, 32, 46073, tzinfo=utc), verbose_name='Starting week of the advertisement'),
        ),
    ]
