# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_auto_20160925_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadAdvetisement',
        ),
    ]
