# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_auto_20161029_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='start_week',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 29, 8, 12, 20, 498355, tzinfo=utc), verbose_name='Starting week of the advertisement'),
        ),
    ]
