# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_uploadadvetisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='time_of_advertisement',
            field=models.IntegerField(default=30),
        ),
    ]
