# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_auto_20160925_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='no_of_slots',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1, max_length=4),
        ),
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='no_of_weeks',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1, max_length=4),
        ),
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='select_bundles',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1, max_length=3),
        ),
    ]
