# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_auto_20161029_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='start_week',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 29, 18, 14, 16, 712018, tzinfo=utc), verbose_name='Starting week of the advertisement'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
