# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_auto_20160930_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadadvetisement',
            name='bussinessPoint_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='uploadadvetisement',
            name='bussinessPoint_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
