# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_auto_20161001_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='Enter_Useranme', max_length=16, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
