# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0017_add_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='upload_Advertisement',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
