# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0018_auto_20161031_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadadvetisement',
            name='no_of_repeats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad_type',
            field=models.CharField(choices=[(1, 'RealEstate'), (2, 'clothing'), (3, 'Jewellery'), (4, 'Movies'), (5, 'TV'), (6, 'radio'), (7, 'footwear'), (8, 'malls'), (9, 'airport'), (10, 'food'), (11, 'fashion'), (12, 'electronics'), (13, 'pharmacy'), (14, 'hospital'), (15, 'print_media'), (16, 'Banks'), (17, 'Theme parks'), (18, 'Tourism'), (19, 'Travel'), (21, 'E-Commerce'), (22, 'Telephone'), (23, 'Mobiles'), (24, 'Grocers'), (25, 'Computers & Accesories'), (26, 'Sports-Outdoors'), (27, 'Furniture'), (28, 'others')], default=1, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Hyderabad', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(default=500032),
        ),
        migrations.AlterField(
            model_name='add_device',
            name='Username',
            field=models.CharField(default='Enter_Useranme', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='add_device',
            name='password',
            field=models.CharField(max_length=62),
        ),
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='no_of_slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='uploadadvetisement',
            name='start_week',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 14, 19, 4, 107921, tzinfo=utc), verbose_name='Starting week of the advertisement'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
