# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField(default=0)),
                ('bundles_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('advertisement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bundles', models.IntegerField(default=10)),
                ('bundles_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('bottom_left_coordinate_x', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
                ('bottom_left_coordinate_y', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.zone'),
        ),
    ]
