# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField(default=0)),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.zone')),
            ],
        ),
    ]
