# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0002_auto_20161102_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='running_slots',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 2, 11, 59, 3, 808791, tzinfo=utc), verbose_name='Starting week of the advertisement'),
        ),
    ]
