# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0002_auto_20161027_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='zone_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=-1)),
                ('no_of_bundles', models.IntegerField(default=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.zone')),
            ],
        ),
        migrations.RemoveField(
            model_name='zone_cost',
            name='zone',
        ),
        migrations.DeleteModel(
            name='zone_cost',
        ),
    ]
