# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0003_auto_20161027_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='bundles_used',
            new_name='bundles_tobegiven',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='bundles_tobegiven',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
