# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0004_auto_20161028_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='running_adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField(default=0)),
                ('given', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.advertisement')),
            ],
        ),
    ]
