# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0004_auto_20161001_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='advertisement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.advertisement'),
        ),
    ]
