# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0005_auto_20161001_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
