# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0005_running_adv'),
    ]

    operations = [
        migrations.CreateModel(
            name='running_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2016, 10, 31, 9, 47, 52, 466690, tzinfo=utc), verbose_name='Starting week of the advertisement')),
            ],
        ),
    ]
