# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0006_running_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='running_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2016, 10, 31, 10, 6, 55, 522550, tzinfo=utc), verbose_name='Starting week of the advertisement')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.zone')),
            ],
        ),
        migrations.DeleteModel(
            name='running_slot',
        ),
    ]
