# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0006_auto_20161001_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='bottom_left_coordinate_x',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='zone',
            name='bottom_left_coordinate_y',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
    ]
