# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssad15', '0007_auto_20161031_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='running_ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField(default=0)),
                ('given', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.advertisement')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssad15.zone')),
            ],
        ),
        migrations.RemoveField(
            model_name='running_adv',
            name='ad',
        ),
        migrations.AlterField(
            model_name='running_slots',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 10, 38, 39, 261487, tzinfo=utc), verbose_name='Starting week of the advertisement'),
        ),
        migrations.DeleteModel(
            name='running_adv',
        ),
    ]
